# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fittergui.ui'
#
# Created: Sun Oct 28 12:59:40 2012
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Specfit(object):
    def setupUi(self, Specfit):
        Specfit.setObjectName(_fromUtf8("Specfit"))
        Specfit.resize(373, 773)
        self.centralwidget = QtGui.QWidget(Specfit)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.Peaklist_Table = QtGui.QTableWidget(self.centralwidget)
        self.Peaklist_Table.setGeometry(QtCore.QRect(0, 0, 361, 691))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Peaklist_Table.sizePolicy().hasHeightForWidth())
        self.Peaklist_Table.setSizePolicy(sizePolicy)
        self.Peaklist_Table.setObjectName(_fromUtf8("Peaklist_Table"))
        self.Peaklist_Table.setColumnCount(4)
        self.Peaklist_Table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.Peaklist_Table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.Peaklist_Table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.Peaklist_Table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.Peaklist_Table.setHorizontalHeaderItem(3, item)
        self.Peaklist_Table.horizontalHeader().setCascadingSectionResizes(False)
        self.Peaklist_Table.horizontalHeader().setHighlightSections(False)
        self.Peaklist_Table.horizontalHeader().setMinimumSectionSize(19)
        self.Peaklist_Table.horizontalHeader().setSortIndicatorShown(False)
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(10, 700, 225, 23))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.label = QtGui.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.addWavelength_doubleSpinBox = QtGui.QDoubleSpinBox(self.splitter)
        self.addWavelength_doubleSpinBox.setDecimals(4)
        self.addWavelength_doubleSpinBox.setMaximum(10000.0)
        self.addWavelength_doubleSpinBox.setSingleStep(0.1)
        self.addWavelength_doubleSpinBox.setObjectName(_fromUtf8("addWavelength_doubleSpinBox"))
        self.addPeak_pushButton = QtGui.QPushButton(self.splitter)
        self.addPeak_pushButton.setObjectName(_fromUtf8("addPeak_pushButton"))
        Specfit.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Specfit)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 373, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFiles = QtGui.QMenu(self.menubar)
        self.menuFiles.setObjectName(_fromUtf8("menuFiles"))
        self.menuCalibrate_Wavelength = QtGui.QMenu(self.menubar)
        self.menuCalibrate_Wavelength.setObjectName(_fromUtf8("menuCalibrate_Wavelength"))
        self.menuPlotter = QtGui.QMenu(self.menubar)
        self.menuPlotter.setObjectName(_fromUtf8("menuPlotter"))
        Specfit.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Specfit)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Specfit.setStatusBar(self.statusbar)
        self.actionOpen_Peaklist = QtGui.QAction(Specfit)
        self.actionOpen_Peaklist.setObjectName(_fromUtf8("actionOpen_Peaklist"))
        self.actionOpen_Spectrum = QtGui.QAction(Specfit)
        self.actionOpen_Spectrum.setObjectName(_fromUtf8("actionOpen_Spectrum"))
        self.actionSet_Workspace = QtGui.QAction(Specfit)
        self.actionSet_Workspace.setObjectName(_fromUtf8("actionSet_Workspace"))
        self.actionManual_fit = QtGui.QAction(Specfit)
        self.actionManual_fit.setObjectName(_fromUtf8("actionManual_fit"))
        self.actionAutomatic_fit = QtGui.QAction(Specfit)
        self.actionAutomatic_fit.setObjectName(_fromUtf8("actionAutomatic_fit"))
        self.actionOpen_Plotter = QtGui.QAction(Specfit)
        self.actionOpen_Plotter.setObjectName(_fromUtf8("actionOpen_Plotter"))
        self.menuFiles.addAction(self.actionOpen_Peaklist)
        self.menuFiles.addAction(self.actionOpen_Spectrum)
        self.menuFiles.addAction(self.actionSet_Workspace)
        self.menuCalibrate_Wavelength.addAction(self.actionManual_fit)
        self.menuCalibrate_Wavelength.addAction(self.actionAutomatic_fit)
        self.menuPlotter.addAction(self.actionOpen_Plotter)
        self.menubar.addAction(self.menuFiles.menuAction())
        self.menubar.addAction(self.menuCalibrate_Wavelength.menuAction())
        self.menubar.addAction(self.menuPlotter.menuAction())

        self.retranslateUi(Specfit)
        QtCore.QObject.connect(self.actionOpen_Peaklist, QtCore.SIGNAL(_fromUtf8("triggered()")), Specfit.open_peaklist)
        QtCore.QObject.connect(self.actionOpen_Spectrum, QtCore.SIGNAL(_fromUtf8("triggered()")), Specfit.open_spectrum)
        QtCore.QObject.connect(self.actionOpen_Plotter, QtCore.SIGNAL(_fromUtf8("triggered()")), Specfit.plot_things)
        QtCore.QObject.connect(self.actionManual_fit, QtCore.SIGNAL(_fromUtf8("triggered()")), Specfit.fit_peaks_manual)
        QtCore.QObject.connect(self.actionAutomatic_fit, QtCore.SIGNAL(_fromUtf8("triggered()")), Specfit.fit_peaks_automatic)
        QtCore.QObject.connect(self.actionSet_Workspace, QtCore.SIGNAL(_fromUtf8("triggered()")), Specfit.set_workspace)
        QtCore.QObject.connect(self.addPeak_pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Specfit.add_peak)
        QtCore.QMetaObject.connectSlotsByName(Specfit)

    def retranslateUi(self, Specfit):
        Specfit.setWindowTitle(QtGui.QApplication.translate("Specfit", "Specfit", None, QtGui.QApplication.UnicodeUTF8))
        item = self.Peaklist_Table.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Specfit", "Fit?", None, QtGui.QApplication.UnicodeUTF8))
        item = self.Peaklist_Table.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Specfit", "Wellenlaenge", None, QtGui.QApplication.UnicodeUTF8))
        item = self.Peaklist_Table.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("Specfit", "Intensitaet", None, QtGui.QApplication.UnicodeUTF8))
        item = self.Peaklist_Table.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("Specfit", "Pixel guess", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Specfit", "Wavelength:", None, QtGui.QApplication.UnicodeUTF8))
        self.addPeak_pushButton.setText(QtGui.QApplication.translate("Specfit", "Add Peak", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFiles.setTitle(QtGui.QApplication.translate("Specfit", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCalibrate_Wavelength.setTitle(QtGui.QApplication.translate("Specfit", "Calibrate Wavelength", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPlotter.setTitle(QtGui.QApplication.translate("Specfit", "Plotter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Peaklist.setText(QtGui.QApplication.translate("Specfit", "Open Peaklist", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Spectrum.setText(QtGui.QApplication.translate("Specfit", "Open Spectrum", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_Workspace.setText(QtGui.QApplication.translate("Specfit", "Set Workspace", None, QtGui.QApplication.UnicodeUTF8))
        self.actionManual_fit.setText(QtGui.QApplication.translate("Specfit", "Manual fit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutomatic_fit.setText(QtGui.QApplication.translate("Specfit", "Automatic fit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Plotter.setText(QtGui.QApplication.translate("Specfit", "Open Plotter", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Specfit = QtGui.QMainWindow()
    ui = Ui_Specfit()
    ui.setupUi(Specfit)
    Specfit.show()
    sys.exit(app.exec_())

